import 'package:flutter/material.dart';

import '../../../core/data/app_history.dart';
import '../data/downtime_excel.dart';
import '../data/downtime_models.dart';

class DowntimePage extends StatefulWidget { const DowntimePage({super.key}); @override State<DowntimePage> createState()=>_DowntimePageState(); }
class _DowntimePageState extends State<DowntimePage>{
  final _storage=DowntimeStorage(); final _category=TextEditingController(text:'Equipment'); final _cause=TextEditingController(); final _note=TextEditingController(); bool _productive=false; DateTime _start=DateTime.now().subtract(const Duration(minutes:10)); DateTime _end=DateTime.now(); List<DowntimeRecord> _records=[];
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{final v=await _storage.load();if(mounted)setState(()=>_records=v);}
  Future<void> _pick(bool start)async{final d=await showDatePicker(context:context,firstDate:DateTime(2020),lastDate:DateTime(2100),initialDate:start?_start:_end);if(d==null||!mounted)return;final t=await showTimePicker(context:context,initialTime:TimeOfDay.fromDateTime(start?_start:_end));if(t==null)return;final v=DateTime(d.year,d.month,d.day,t.hour,t.minute);setState(()=>start?_start=v:_end=v);}
  Future<void> _add()async{if(_cause.text.trim().isEmpty)return;final r=DowntimeRecord(id:DateTime.now().microsecondsSinceEpoch.toString(),category:_category.text.trim(),cause:_cause.text.trim(),start:_start,end:_end,productive:_productive,note:_note.text.trim());final n=[..._records,r];await _storage.save(n);await AppHistoryStorage().add(HistoryEntry(module:'Downtime',title:r.cause,subtitle:'${r.duration.inMinutes} min • ${r.category}'));_cause.clear();_note.clear();if(mounted)setState(()=>_records=n);}
  @override void dispose(){for(final c in [_category,_cause,_note])c.dispose();super.dispose();}
  @override Widget build(BuildContext context){final total=_records.fold<Duration>(Duration.zero,(s,r)=>s+r.duration);return Scaffold(appBar:AppBar(title:const Text('Downtime')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:_category,decoration:const InputDecoration(labelText:'Category')),TextField(controller:_cause,decoration:const InputDecoration(labelText:'Cause')),Row(children:[Expanded(child:ListTile(contentPadding:EdgeInsets.zero,title:const Text('Start'),subtitle:Text(_start.toString()),onTap:()=>_pick(true))),Expanded(child:ListTile(contentPadding:EdgeInsets.zero,title:const Text('End'),subtitle:Text(_end.toString()),onTap:()=>_pick(false)))]),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Productive / NVA emas'),value:_productive,onChanged:(v)=>setState(()=>_productive=v)),TextField(controller:_note,decoration:const InputDecoration(labelText:'Note')),const SizedBox(height:10),Row(children:[Expanded(child:FilledButton.icon(onPressed:_add,icon:const Icon(Icons.add),label:const Text('Qayd etish'))),const SizedBox(width:10),OutlinedButton.icon(onPressed:()=>DowntimeExcel().importRecords().then((v){if(v!=null&&mounted){final n=[..._records,...v];_storage.save(n);setState(()=>_records=n);}}),icon:const Icon(Icons.file_open_outlined),label:const Text('Import')),const SizedBox(width:10),OutlinedButton.icon(onPressed:_records.isEmpty?null:()=>DowntimeExcel().export(_records),icon:const Icon(Icons.table_view),label:const Text('Excel'))]),const SizedBox(height:16),Card(child:ListTile(title:const Text('Jami downtime'),subtitle:Text('${total.inMinutes} min ${total.inSeconds%60} s'),trailing:Text('${_records.length} yozuv'))),..._records.reversed.map((r)=>Card(child:ListTile(title:Text(r.cause),subtitle:Text('${r.category} • ${r.duration.inMinutes} min • ${r.productive?'Productive':'NVA'}'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{final n=_records.where((x)=>x.id!=r.id).toList();await _storage.save(n);if(mounted)setState(()=>_records=n);}))) ]));}
}
